<?php echo $this->flashMessages(); ?>
<div class="panel panel-default">
    <div class="panel-body">
    <?php
     $form->setAttribute('role', 'form');
     $form->prepare();

     echo $this->form()->openTag($form);
     ?>
            <?php echo $this->formHidden($form->get('csrf')); ?>
            <?php $classError = $this->FormElementErrors($form->get('FirstName')) ? 'has-error' : '';?>
            <div class="form-group <?php echo $classError;?>">
                <?php echo $this->formInput($form->get('FirstName')); ?>
            </div>

            <?php $classError = $this->FormElementErrors($form->get('LastName')) ? 'has-error' : '';?>
            <div class="form-group <?php echo $classError;?>">
                <?php echo $this->formInput($form->get('LastName')); ?>
            </div>

            <?php $classError = $this->FormElementErrors($form->get('Email')) ? 'has-error' : '';?>
            <div class="form-group <?php echo $classError;?>">
                <?php echo $this->formInput($form->get('Email')); ?>
            </div>

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <?php $classError = $this->FormElementErrors($form->get('Password')) ? 'has-error' : '';?>
                    <div class="form-group <?php echo $classError;?>">
                        <?php echo $this->formInput($form->get('Password')); ?>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <?php $classError = $this->FormElementErrors($form->get('PasswordVerify')) ? 'has-error' : '';?>
                    <div class="form-group <?php echo $classError;?>">
                        <?php echo $this->formInput($form->get('PasswordVerify')); ?>
                    </div>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
